### ISSUE TITLE
スケッチをzip圧縮せずに公開してほしい

### ISSUE THREAD

**Issue by ka-yamano** [Leafony/Sample-Sketches#1]
# 現状の仕様

Leafonyのサンプルスケッチが全てzip圧縮された状態でコミットされています。

# 現状仕様の問題点

Gitでは圧縮ファイルの中身まで確認してコミット間の差分をとることができません。
また、GitHub上でもソースコードを確認できない状態になっています。

# 提案する仕様

展開しても動作に支障がないスケッチが同梱されたzipファイルであれば展開し、その中身をGitでバージョン管理します。

## 提案内容におけるメリット

Gitによるバージョン管理の恩恵を受けることができるようになります。
OSSとしてより貢献しやすくなると思われます。

## 提案内容におけるデメリット

[トリリオンノード研究会のWeb Bluetoothの記事](https://trillion-node.org/example/webbluetooth/)などのサンプルスケッチへのリンクがおそらくリンク切れになります。

**Comment by ka-yamano** [comment]
@Leafony 
ご対応ありがとうございます:pray:

しかし、一部のディレクトリで必要なファイルが欠けてしまっているようです。
例えば`PIR_Melody_test`スケッチ(cf7a6020012a280feb17154bf77e411006d643dd)では`pitches.h`がincludeされていますが、対応するヘッダファイルが存在していません。

これからいくつか触っていく予定なので、自分が触ったサンプルスケッチに関しては動作するようにPull Requestを作成していこうと考えています。

**Comment by Leafony** [comment]
ka-yamano-san

以下、修正しました。よろしくお願いいたします。

>しかし、一部のディレクトリで必要なファイルが欠けてしまっているようです。
>例えばPIR_Melody_testスケッチ(cf7a602)ではpitches.hがincludeされていますが、対応するヘッダ>ファイルが存在していません。
